### ISSUE TITLE
RFC: Rebalancing Seed Rewards for Unripe Assets

### ISSUE THREAD

**Issue by bacchist** [BeanstalkFarms/Beanstalk#105]
## Problem

Beanstalk has been unable to bring the price of Bean back to $1 after the most recent cross below peg on September 19, despite sufficient assets available for conversion in the Silo. The magnitude of the deviation from peg is far greater than the trading fee on the Curve pool, which suggests that Silo incentives are less than optimal.

Currently, Unripe assets in the Silo are allocated Stalk and Seed proportionate to new deposits made to the Silo. For example, urBEAN deposits to the Silo are allocated Stalk and Seed at a 1:2 ratio, just like BEAN deposits. Similarly, urBEAN3CRV deposits to the Silo are allocated Stalk and Seed at a 1:4 ratio, just like BEAN3CRV deposits.

The opportunity cost presented by this imbalance is a significant deterrence to conversions from urBEAN3CRV to urBEAN below peg. The quantity of Seeds lost in the process will produce the amount of Stalk earned within days. Unless a Silo member anticipates being able to quickly convert back to urBEAN3CRV, they will lose ground to other Silo members, diminishing their share of future Bean seignorage.

Additionally, since Beanstalk's replant, new participation in the Silo has been lackluster. Although there was an initial spike in Silo participation after the replant, with >$5M BEAN3CRV deposited then, Silo participation has since dwindled to <$1M BEAN3CRV. It is likely that the similarity in the Stalk:Seed allocation between Unripe assets and new assets deposited to the Silo may be a deterrent to new users considering engaging in Beanstalk, as new deposits currently accrue Grown Stalk at the same rate as their counterpart Unripe assets, despite the fact that new deposits are more markedly supporting the protocol's growth and stability since the replant vis-a-vis their provision of non-BEAN liquidity.

## Proposed Solution

Given that it is likely that the majority of the liquidity represented by Unripe LP tokens will remain in the Curve pool until those assets ripen, there is less need to use Seed rewards to incentivize liquidity for Bean to trade against. By equalizing the Stalk:Seed allocation for all Unripe assets, the opportunity cost in the loss of Seeds when converting from urBEAN3CRV to urBEAN when BEAN is trading below peg would be removed, thus reducing friction and fostering a greater incentive to participate in peg maintenance by Unripe asset holders.

**Solution:** Reduce the Stalk:Seed allocation for all Unripe assets deposited to the Silo down to 1:1. This would incentivize Unripe asset holders to more actively participate in peg maintenance, while also acknowledging and incentivizing greater participation of new users in the Silo.

**Comment by publiuss** [comment]
For reference, changing the # of Seeds per BDV of a Silo Whitelisted asset is something that has never been performed before. Unfortunately, Silo V2 does not natively support the modification of the number of Seeds per BDV of a Whitelisted Silo asset. 

For transparency purposes, here is our thoughts on the technical 

## Technical Walkthrough

A user's balance of Seeds is set to the summation of the `seedsPerBDV * bdv` at the time of deposit (Not the current seedsPerBDV) for all their Deposits.

If Stalk Holders decrement the `s.ss[token].seeds` stalk variable (seedsPerBDV of a given token), all new Deposits will use the new `s.ss[token].seeds`, but old Deposits will not automatically be updated to use the new value. Functions that remove Deposits (`enrootDeposit(s)`, `convert`, `transferDeposit(s)`, `withdrawDeposit(s)`) will burn the incorrect amount of Seeds when removing old Deposits because these Deposits were Deposited with a different `s.ss[token].seeds` value.

This proposal proposes to decrement `s.ss[token].seeds` of two different Whitelisted ERC-20 tokens.

## Technical Implementation

In order to facilitate this, we need to:
1. Decrement `s.ss[token].seeds` value in `storage`'
2. Migrate all Deposits with a new `s.ss[token].seeds` value in an account before they interact with `enrootDeposit(s)`, `convert`, `transferDeposit(s)` and `withdrawDeposit(s)`

(1) is quite trivial through a 1 time function call, but (2) is not.

There are two technical ways to do this (2):
a. Permissioned Automatic Migration: Migrate every account at the time of modification
b. Permissionless Manual Migration: Force accounts to manually migrate before they can interact with the Silo.

### Permissioned Automatic Migration
Permissioned Automatic Migration Migration would require trust that a specific account (Ex. the BCM) performs the migration correctly at the time that (1) happens. This would be far cheaper gas wise. Permissioned migration could be done through a 1 time migration script. Permissioned on-chain action is never ideal.

### Permissionless
Permissionless Manual Migration would mandate that a Farmer update their Seeds balance through a `migrate` function before they use the Silo. Any account could migrate any account and thus a public goods actor could still manually perform the migration as soon as (1) occurs (Ex. BF/BS). Thus, the Farmer user experience could still feel seemless as they won't have to manually migrate. Migration could also be automated at the UI level such that the UI would automatically call `migrate` through a `farm` function call when a Farmer first interacts with the Silo. In this case, bots would still have to manually figure out how to migrate. Manual Migration would require a full upgrade of the Silo.

Permissionless Migration requires be on-chain verification of Seed balances, which means:
1. Farmers would have to submit all of their non-zero Token, Season Silo Deposit pairings in a function, which could be hard for users to do without the aid of an off-chain script/UI.
2. Migration Is far less gas efficient. The `migrate` function would be relatively more expensive as it would need to read the value of all of their Deposits on-chain (Requires a $G_{coldsload}$, which is 2100 gas).

## Additional Thoughts
- If done once, this process could easily be generalized to perform again if in the future Stalk Holders wanted to change another `seedsPerBDV` function. 
- A Stalk Gauge system is proposed in Silo V3, which will make this process unnecessary, so such a feature would only be useful in the short term. Development of Silo V3 will possibly start after the completion of Wells, but will take a substantial amount of time to build.
