### ISSUE TITLE
Navigating straight to a listing/order fails to rehydrate position data

### ISSUE THREAD

**Issue by silochad** [BeanstalkFarms/Beanstalk#189]
Before refresh and after refresh:

<img width="1127" alt="image" src="https://user-images.githubusercontent.com/99763686/209745418-8bd00508-92e6-4a3c-9856-aecaf9a4e309.png">
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/99763686/209745442-8143f518-0a5f-454a-8257-d660230b501f.png">

The graph is forgetting the pixel position of the selected listing/order during refresh, so believe it's drawing the lines & annotation at (0, 0).

**Comment by tansanDOTeth** [comment]
I was inspecting this bug and found more issues with this particular graph. 

1. Select a point
2. Resize the window vertically
3. You'll see that the horizontal and vertical line hasn't been redrawn to the new scale.

![image](https://user-images.githubusercontent.com/92072158/212537191-c89caab7-54af-48cd-a54f-379f52cf3238.png)

**Comment by tansanDOTeth** [comment]
I don't have the project setup, but looks like the bug is around here. The cursorPoint is memoized, so it's not being updated when the `selectedPoint` hasn't changed during the window resize. I am sure the charting system has an onChange callback that can be used to set the new `selectedPoint` and similarly on first load so it can trigger that memoization.

https://github.com/BeanstalkFarms/Beanstalk/blob/master/projects/ui/src/components/Market/PodsV2/Modules/MarketGraph.tsx#L268

**Comment by tansanDOTeth** [comment]
@silochad Could you assign this to me please?
