### ISSUE TITLE
RFC: Soil Issuance Improvement

### ISSUE THREAD

**Issue by Brean0** [BeanstalkFarms/Beanstalk#86]
## Problem
From Season to Season, the Temperature changes at most of +/-3% based on the Current State of Beanstalk. In instances where demand for Soil exceeds supply, Beanstalk is likely paying significantly more than what is needed to attract creditors. While Beanstalk would rather have too high of a Temperature rather than one that is too low, such that Beanstalk may not attract sufficient credit when the demand for Soil inevitably decreases, the Temperature Beanstalk offers for Sowing Beans can be better optimized for during times of excess demand. 

## Proposed Solution

Introduce a dutch auction during the first $b$ blocks after the `sunrise()` call, where the Temperature ramps from 1% to 100% of the maximum Temperature. The first X blocks after the `sunrise()` call will be referred to as the `Morning` of each Season. The auction is called the "the Morning Auction".

The Soil issued when $0 < \Delta B_{t-1}$ is no longer constant, and is now a function of the results of the Morning Auction. Instead, when $0 < \Delta B_{t-1}$, the maximum potential Pods issued within a Season is constant. 

## Specification

1. Redefine all instances of $h_t$ as the maximum Temperature $h_t^{\text{max}}$.

2. Redefine $h$ to:

$$ h =
\begin{cases}
{1} & if \quad c = 0 \\
{max(h_t^{\text{max}}*log_{ab+1}(ac+1),1)} & if \quad 0 < c  < 25 \\
{h_t^{\text{max}}} & else 
\end{cases} $$

where $a$ is the control variable, $b$ is the number of blocks needed to elapse to reach the maximum Temperature, and $c$ is the number of blocks that has elapsed since the `sunrise()` call.

$$
\begin{aligned}
a =& \ 2 \\
b =& \ 25 \ (i.e \ \text{25 blocks until Temperature reaches its max)} \\
c =& \ \text{currentBlock} \ - \text{sunriseBlock}
\end{aligned}
$$

3. Adjust the time in which Beanstalk considers demand for Soil increasing in instances where all but at most one Soil is Sown from 5 minutes to 10 minutes (*i.e.*, $\Delta{E_{t-1}^{u^{first}}} \leq 600$).

4. When $\Delta B_{t-1} > 0$, Fix the maximum Pods that can be issued during a Season based on the number of Harvestable Pods at the start of that Season, instead of the Soil.

### Storage
The following changes are made to Beanstalk's storage:

Add to the `Season` struct: `uint32 sunriseBlock`;
Add to the `Season` struct: `bool AbovePeg`;
Add to the `Field` struct: `uint128 beanSown`;
Modify `soil` in the `Season` struct from datatype `uint256` to `uint128` ;
Deprecate `startSoil` from the Weather struct in favor of `beanSown`.

### Existing Functions in scope
**SeasonFacet**
* `stepSeason()`
* `stepWeather(int256 deltaB):`

**LibDibbler**
* `sow(uint256 amount, address account)`
* `beansToPods(uint256 beans, uint256 weather)`

**FieldFacet**

* `sow(uint256 amount, LibTransfer.From mode)` 
* `sowNoSoil(uint256 amount, address account)`
* `sowWithMin(uint256 amount, uint256 minAmount, LibTransfer.From mode)`
* `totalSoil()`

### New Functions/Getters: 
**LibDibbler**
* `morningAuction(uint256 maxWeather, uint256 _block)` - outputs the new scaled weather as a function of the maximum weather and the blocks elapsed since sunrise.
* `auctionMath(uint256 a)` - Math Helper for Morning Auction.
* `beansToPodsAbovePeg(uint256 beans, uint256 maxPeas)` - issue pods when bean is above peg. 

**FieldFacet**
* `yield()` -  outputs the instantaneous temperature in the season (previous functionality is retained via `maxYield()` in the WeatherFacet).
* `peas()` - outputs Peas, or the amount of pods beanstalk is willing to issue. 

**SeasonFacet** 
* `abovePeg()` - getter for `bool abovePeg`
* `sunriseBlock()` - getter for `uint32 sunriseBlock`

## Technical Implementation: 

With this change, the Temperature is dynamic within the Season. 

When $0 < \Delta B_{t-1}$, the Soil issued within the Season is dynamic, while the maximum Pods issued is fixed. When $\Delta B_{t-1} < 0$, the Soil issued during a Season is fixed, while the maximum Pods issued is dynamic. 

![image](https://user-images.githubusercontent.com/90539204/198854968-636583c3-9c78-40fd-bb45-b157a87d69e7.png)

Over the first $b$ blocks within each Season, the Temperature starts at 1% and ramps up to 100% of the maximum Temperature. The formula can be seen here:  https://www.desmos.com/calculator/soynntzc7h 

`s.f.soil` and `totalSoil()` now behave differently based on $\Delta B_{t-1}$. 
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/90539204/196532150-7d537257-1c1d-477f-9036-44adcd888467.png"> 

## Execution
Estimated development time: **2-3 weeks** .

1. Push proof-of-concept PR.
2. Beanstalk Farms code review.
3. External audit.
6. BIP.

**Comment by silochad** [comment]
## Call notes: 09/08/2022 (DAO Meeting)

Discussed during the DAO meeting on 9/8. 

Visualization of $h$: https://www.desmos.com/calculator/soynntzc7h

**Comment by BrianOlympus** [comment]
## 09/17/2022 (RFC revision): 


> ## Call notes: 09/08/2022 (DAO Meeting)
> Discussed during the DAO meeting on 9/8.
> 
> Visualization of h: https://www.desmos.com/calculator/soynntzc7h

**Comment by BrianOlympus** [comment]
### RFC: Revision 09/17/2022

added a change on how soil is issued when deltaB > 0. 

## Abstract

Introduce a dutch auction during the first X blocks after the `sunrise()` call, where the Temperature ramps from 1% to 100% of the max Temperature. This time period will be referred as the `morning` within a season, and the mechanism named "the Morning Auction" (WIP)

Revise how soil is issued when `DeltaB > 0`, such that a maximum amount of pods that can be issued per season is constant. 


## Motivation
Currently, the Temperature changes a maximum of +/-3% based on the state of Beanstalk. In instances where short-term demand exceeds short-term supply, Beanstalk may be paying significantly more than what is needed to attract creditors. While Beanstalk would rather have too high of a Temperature rather than too low and risk not attracting creditors at all, the Temperature can better optimize during times of excess demand. 

With the change above, an additional change should be added on how soil is issued when deltaB > 0. When farmers sow during the morning, assuming soil is fully sown, it results in less pods issued than what beanstalk allowed. This potentially leads to an inefficiency in measuring soil demand and debt issuance in general. Instead, we change how soil is issued such that the potential pods that can be issued will always be able to be sown throughout the season. 

### Example: 
100 pods were harvested in the previous season. Current weather is 900%.  Currently, that means that Beanstalk will issue 100/(1+9) = 10 soil. 

With the morning auction, if someone sows beans at the earliest block possible, only 10* 1.01 = 10.1 pods would be issued. With this change, we would instead issue 100/1.01 = 99.009901 soil, meaning the same scenario would issue the 100 pods intended instead. As the dutch auction proceeds, the amount of soil decreases, until the temperature reaches its maximum (this does not include the soil coefficient at high and low podrate).

## Specification

1. Redefine all instances of $h_t$ as the maximum Temperature $h_t^{\text{max}}$.

2. Redefine $h$ to:

$$ h =
\begin{cases}
{1} & if \quad c = 0 \\
{h_t^{\text{max}}*log_{ab+1}(ac+1)} & if \quad 0 < c  < 25 \\
{h_t^{\text{max}}} & else 
\end{cases} $$

where $a$ is the control variable, $b$ is the number of blocks needed to elapse to reach max Temperature, and $c$ is the number of blocks that has elapsed since the `sunrise()` call.

$$
\begin{aligned}
a =& \ 2 \\
b =& \ 25 \ (i.e \ \text{25 blocks until Temperature reaches its max)} \\
c =& \ \text{currentBlock} \ - \text{sunriseBlock}
\end{aligned}
$$

3. Adjust the time in which Beanstalk considers demand for Soil increasing in instances where all but at most one Soil is Sown from 5 minutes to 10 minutes (*i.e.*, $\Delta{E_{t-1}^{u^{first}}} \leq 600$).



### Storage
Add to the `Season` struct: `uint32 sunriseBlock`.

### Existing Functions in scope
**SeasonFacet**
* `stepSeason()`

**LibDibbler**
* `sow(uint256 amount, address account)`
* `BeansToPods(uint256 beans, uint256 weather)`

**FieldFacet**

*`sow(uint256 amount, LibTransfer.From mode)` 
*`sowWithMin(uint256 amount, uint256 minAmount, LibTransfer.From mode)`
*`totalSoil()`

**weather**
*`stepWeather(int256 deltaB):


#### New Functions/Getters: 
**LibDibbler**
* `MorningAuction()` - outputs the new scaled weather as a function of the maximum weather and the blocks elapsed since sunrise


**FieldFacet**
* `getMorningYield()` -  outputs the instantaneous temperature in the season (max temp has a getter via `yield()`
* `totalPeas()` - outputs Peas, or the amount of pods beanstalk is willing to issue. 


## Execution
Estimated development time: **2-3 weeks**.

1. Push proof-of-concept PR.
2. Beanstalk Farms code review.
3. External audit.
5. BIP.
